---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: gurupavani
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Debug Docker SDK
      debug:
        msg: "Docker SDK installed: {{ 'docker' in ansible_python_version }}"
#      verbosity: 2
    - name: Pull Docker Image
      docker_image:
        name: "gurupavani31/calculator-spe"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator-spe gurupavani31/calculator-spe
