---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
    
    - name: Pull docker image
      shell: docker pull gurupavani31/calculator-spe
     
    - name: Running container
      shell: docker run -it -d --name calculator-spe-container gurupavani31/calculator-spe
